# Generated by Django 5.1.6 on 2025-03-06 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edif',
            fields=[
                ('id_edif', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_edif', models.CharField(blank=True, max_length=255, null=True)),
                ('rif', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion_edif', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_edif', models.ImageField(blank=True, null=True, upload_to='edificios/')),
                ('campo_temporal', models.CharField(blank=True, max_length=10, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='editar_edificio.authuser')),
            ],
            options={
                'db_table': 'edif',
                'managed': True,
            },
        ),
    ]
