# Generated by Django 5.1.6 on 2025-03-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editar_edificio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edif',
            name='campo_temporal',
        ),
        migrations.AlterField(
            model_name='edif',
            name='foto_edif',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
