# Generated by Django 5.1.6 on 2025-03-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editar_edificio', '0002_remove_edif_campo_temporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edif',
            name='foto_edif',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
