# Generated by Django 5.1.6 on 2025-03-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editar_edificio', '0003_alter_edif_foto_edif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edif',
            options={'managed': False},
        ),
    ]
