# Generated by Django 5.1.4 on 2025-02-17 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dpto',
            fields=[
                ('nro_dpto', models.IntegerField(primary_key=True, serialize=False)),
                ('alicuota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('id_edif', models.IntegerField()),
            ],
            options={
                'db_table': 'dpto',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_prop', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'propietario',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('nro_dpto', models.ForeignKey(db_column='nro_dpto', on_delete=django.db.models.deletion.CASCADE, to='gestion_propietario.dpto')),
                ('id_prop', models.ForeignKey(db_column='id_prop', on_delete=django.db.models.deletion.CASCADE, to='gestion_propietario.propietario')),
            ],
            options={
                'db_table': 'asignacion',
                'unique_together': {('id_prop', 'nro_dpto', 'fecha_inicio')},
            },
        ),
    ]
