# Generated by Django 5.1.4 on 2025-02-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propietario', '0001_initial'),
    ]

    operations = [
    ]
