# Generated by Django 5.1.6 on 2025-03-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propietario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asignacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('correo', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'correo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dpto',
            fields=[
                ('id_dpto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('alicuota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('id_edif', models.IntegerField()),
            ],
            options={
                'db_table': 'dpto',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='propietario',
            options={'managed': False},
        ),
    ]
