# Generated by Django 5.1.6 on 2025-02-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propietario', '0002_auto_20250216_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('correo', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'correo',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='asignacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dpto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='propietario',
            options={'managed': False},
        ),
    ]
