# Generated by Django 5.1.6 on 2025-03-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propietario', '0002_asignacion_correo_dpto_alter_propietario_options'),
        ('gestion_propietario', '0003_correo_alter_asignacion_options_alter_dpto_options_and_more'),
    ]

    operations = [
    ]
