# Generated by Django 5.1.6 on 2025-03-10 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propietario', '0004_merge_20250305_2207'),
        ('gestion_propietario', '0004_merge_20250305_2347'),
    ]

    operations = [
    ]
