# Generated by Django 5.1.6 on 2025-03-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propietario', '0005_merge_20250309_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_com', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'comentario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComentarioFrec',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_comentario', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'comentario_frec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id_deuda', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cta', models.DateTimeField()),
                ('deuda', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('detalle_deuda', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'deuda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edif',
            fields=[
                ('id_edif', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_edif', models.CharField(blank=True, max_length=255, null=True)),
                ('rif', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion_edif', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_edif', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edif',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id_fondo', models.AutoField(primary_key=True, serialize=False)),
                ('moneda_fondo', models.CharField(blank=True, null=True)),
                ('egresos', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('ingresos', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('saldo_fondo', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('fecha_fondo', models.DateTimeField(blank=True, null=True)),
                ('detalles_fondo', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'fondo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_gasto', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle_gasto', models.CharField(blank=True, max_length=255, null=True)),
                ('monto_gasto_bs', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('monto_gasto_dl', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('moneda_gasto', models.CharField(blank=True, null=True)),
                ('fecha_gasto', models.DateTimeField(blank=True, null=True)),
                ('clasificacion_gasto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gasto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Importe',
            fields=[
                ('id_importe', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_importe', models.DateTimeField()),
                ('pago_bs', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('pago_dl', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('moneda_importe', models.CharField(blank=True, null=True)),
                ('detalle_importe', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'importe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_pres', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_pres', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle_pres', models.CharField(blank=True, max_length=255, null=True)),
                ('monto_pres_bs', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('monto_pres_dl', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('moneda_pres', models.CharField(blank=True, null=True)),
                ('fecha_pres', models.DateTimeField(blank=True, null=True)),
                ('clasificacion_pres', models.TextField(blank=True, null=True)),
                ('tipo_pres', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'presupuesto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recibo', models.DateTimeField(blank=True, null=True)),
                ('monto_dl', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
            ],
            options={
                'db_table': 'recibo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReciboP',
            fields=[
                ('id_recibo_p', models.AutoField(primary_key=True, serialize=False)),
                ('monto_dl', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
            ],
            options={
                'db_table': 'recibo_p',
                'managed': False,
            },
        ),
    ]
