# Generated by Django 5.1.6 on 2025-03-16 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dpto',
            fields=[
                ('id_dpto', models.CharField(choices=[('11', 'Dpto 11'), ('12', 'Dpto 12'), ('13', 'Dpto 13'), ('21', 'Dpto 21'), ('22', 'Dpto 22'), ('23', 'Dpto 23'), ('31', 'Dpto 31'), ('32', 'Dpto 32')], primary_key=True, serialize=False)),
                ('alicuota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('id_edif', models.IntegerField()),
            ],
            options={
                'db_table': 'dpto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id_fondo', models.IntegerField(primary_key=True, serialize=False)),
                ('moneda_fondo', models.CharField(choices=[('$', 'Dólares ($)'), ('bs', 'Bolivares (Bs. S)')], max_length=10)),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('egresos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo_fondo', models.DecimalField(decimal_places=2, max_digits=30, max_length=30)),
                ('fecha_fondo', models.DateTimeField()),
                ('detalles_fondo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fondo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id_gasto', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo_gasto', models.CharField(max_length=100)),
                ('detalle_gasto', models.CharField(max_length=255)),
                ('monto_gasto_bs', models.DecimalField(decimal_places=2, max_digits=30)),
                ('monto_gasto_dl', models.DecimalField(decimal_places=2, max_digits=30)),
                ('moneda_gasto', models.CharField(max_length=1)),
                ('fecha_gasto', models.DateTimeField()),
                ('clasificacion_gasto', models.CharField()),
            ],
            options={
                'db_table': 'gasto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_pres', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo_pres', models.CharField(max_length=100)),
                ('detalle_pres', models.CharField(max_length=255)),
                ('monto_pres_bs', models.DecimalField(decimal_places=2, max_digits=30)),
                ('monto_pres_dl', models.DecimalField(decimal_places=2, max_digits=30)),
                ('fecha_pres', models.DateTimeField()),
                ('clasificacion_pres', models.CharField()),
                ('tipo_pres', models.CharField()),
            ],
            options={
                'db_table': 'presupuesto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id_recibo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_recibo', models.DateTimeField()),
                ('monto_dl', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'recibo',
                'managed': False,
            },
        ),
    ]
