# Generated by Django 5.1.6 on 2025-02-25 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dpto',
            fields=[
                ('id_dpto', models.CharField(primary_key=True, serialize=False)),
                ('alicuota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('id_edif', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='importe',
            fields=[
                ('id_importe', models.IntegerField(primary_key=True, serialize=False)),
                ('id_fondo', models.IntegerField()),
                ('fecha_importe', models.DateTimeField()),
                ('pago_bs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_dl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_dpto', models.ForeignKey(choices=[('11', 'Dept 11'), ('12', 'Dept 12'), ('13', 'Dept 13'), ('21', 'Dept 21'), ('22', 'Dept 22'), ('23', 'Dept 23'), ('31', 'Dept 31'), ('32', 'Dept 32')], db_column='id_dpto', on_delete=django.db.models.deletion.CASCADE, to='gestion_capital.dpto')),
            ],
        ),
    ]
