# Generated by Django 5.1.6 on 2025-02-25 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_capital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='importe',
            options={'managed': False},
        ),
    ]
