# Generated by Django 5.1.6 on 2025-02-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_capital', '0002_alter_dpto_options_alter_importe_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dpto',
            table='dpto',
        ),
        migrations.AlterModelTable(
            name='importe',
            table='importe',
        ),
    ]
