# Generated by Django 5.1.6 on 2025-03-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_capital', '0003_alter_dpto_table_alter_importe_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asignacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_prop', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prop', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'propietario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id_recibo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_recibo', models.DateTimeField()),
            ],
            options={
                'db_table': 'recibo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recibo_p',
            fields=[
                ('id_recibo_p', models.IntegerField(primary_key=True, serialize=False)),
                ('monto_dl', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'recibo_p',
                'managed': False,
            },
        ),
    ]
