# Generated by Django 5.1.6 on 2025-03-15 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_capital', '0004_asignacion_propietario_recibo_recibo_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id_deuda', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cta', models.DateTimeField()),
                ('deuda', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('detalle_deuda', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'deuda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id_fondo', models.IntegerField(primary_key=True, serialize=False)),
                ('moneda_fondo', models.CharField(choices=[('$', 'Dólares ($)'), ('bs', 'Bolivares (Bs. S)')], max_length=10)),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('egresos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo_fondo', models.DecimalField(decimal_places=2, max_digits=30, max_length=30)),
                ('fecha_fondo', models.DateTimeField()),
                ('detalles_fondo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fondo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_gasto', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle_gasto', models.CharField(blank=True, max_length=255, null=True)),
                ('monto_gasto_bs', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('monto_gasto_dl', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('moneda_gasto', models.CharField(blank=True, null=True)),
                ('fecha_gasto', models.DateTimeField(blank=True, null=True)),
                ('clasificacion_gasto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gasto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_pres', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_pres', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle_pres', models.CharField(blank=True, max_length=255, null=True)),
                ('monto_pres_bs', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('monto_pres_dl', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('moneda_pres', models.CharField(blank=True, null=True)),
                ('fecha_pres', models.DateTimeField(blank=True, null=True)),
                ('clasificacion_pres', models.TextField(blank=True, null=True)),
                ('tipo_pres', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'presupuesto',
                'managed': False,
            },
        ),
    ]
